#!/usr/bin/env bash
# Copyright The Orca Authors
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

cd "$(dirname "$0")/.."

node scripts/utils/sync-version.cjs

yarn tsc --noEmit -p tsconfig.json
yarn eslint .
node scripts/utils/license-headers.cjs
