// Copyright The Orca Authors
// SPDX-License-Identifier: Apache-2.0

export {
  Orca as default,
  Orca,
  BaseOrca,
  type ApiKeySetter,
  type OrcaOptions,
  type Logger,
  type LogLevel,
} from './client';
export { VERSION } from './version';
export {
  OrcaError,
  ExtensionNotAvailableError,
  APIError,
  APIUserAbortError,
  APIConnectionError,
  APIConnectionTimeoutError,
  BadRequestError,
  AuthenticationError,
  PermissionDeniedError,
  NotFoundError,
  ConflictError,
  UnprocessableEntityError,
  RateLimitError,
  InternalServerError,
  type ErrorType,
} from './core/error';
export { APIResource } from './core/resource';
export { APIPromise } from './core/api-promise';
export { PageCursor, type PageCursorParams, type PageCursorResponse, PagePromise } from './pagination';
export { Stream, type ServerSentEvent } from './core/streaming';
export { toFile, type Uploadable, type ToFileInput } from './uploads';

// ---- Resources -----------------------------------------------------------

export { Agents, Versions } from './resources/agents';
export type {
  Agent,
  AgentResponseModel,
  AgentResponseSkillDefinition,
  ModelConfig,
  ModelEffort,
  ModelEffortType,
  McpServerDefinition,
  AgentMcpServerInput,
  AgentCustomToolInputSchema,
  AgentPermissionPolicy,
  AgentNamedToolConfig,
  AgentToolConfigs,
  AgentToolDefinition,
  AgentToolDefaultConfig,
  AgentBuiltinToolsetDefinition,
  AgentMcpToolsetDefinition,
  AgentCustomToolDefinition,
  AgentSkillDefinition,
  AgentMultiagentDefinition,
  AgentMultiagentRosterEntry,
  AgentCreateParams,
  AgentUpdateParams,
  AgentListParams,
  AgentRetrieveParams,
  VersionListParams,
} from './resources/agents';

export { Sessions, Events, SessionFiles, Resources, Threads, ThreadEvents } from './resources/sessions';
export type {
  Session,
  SessionAgent,
  SessionAgentMember,
  DeletedSession,
  OutcomeEvaluation,
  SessionAgentInput,
  SessionAgentReference,
  SessionAgentUpdate,
  SessionAgentWithOverrides,
  SessionDefineOutcomeInitialEvent,
  SessionInitialEvent,
  SessionStatus,
  SessionStats,
  SessionTiming,
  SessionUserMessageInitialEvent,
  SessionUsage,
  SessionCacheCreationUsage,
  SessionCreateParams,
  SessionUpdateParams,
  SessionListParams,
  SessionEvent,
  EventListParams,
  EventSendParams,
  EventSendResponse,
  EventStreamParams,
  Base64ContentSource,
  BinaryContentSource,
  DocumentContentBlock,
  FileContentSource,
  ImageContentBlock,
  MessageContentBlock,
  NonEmptyArray,
  OutcomeRubric,
  SearchResultContentBlock,
  SessionCustomToolResultEventInput,
  SessionDefineOutcomeEventInput,
  SessionEventInput,
  SessionInterruptEventInput,
  SessionSystemMessageEventInput,
  SessionToolConfirmationEventInput,
  SessionToolResultEventInput,
  SessionUserMessageEventInput,
  TextContentBlock,
  TextDocumentSource,
  ToolResultContentBlock,
  URLContentSource,
  DeletedSessionFile,
  SessionFile,
  SessionFileListParams,
  SessionResource,
  DeletedSessionResource,
  SessionFileResource,
  SessionMemoryStoreResource,
  SessionRepositoryResource,
  SessionResourceBase,
  SessionResourceBranchCheckout,
  SessionResourceCheckout,
  SessionResourceCheckoutConfig,
  SessionResourceCommitCheckout,
  SessionResourceRequest,
  SessionResourceRequestBase,
  FileSessionResourceRequest,
  MemoryStoreSessionResourceRequest,
  RepositorySessionResourceRequest,
  ResourceAddParams,
  ResourceUpdateParams,
  ResourceListParams,
  SessionThread,
  SessionThreadStatus,
  SessionThreadStats,
  SessionThreadUsage,
  ThreadListParams,
  ThreadEventListParams,
  ThreadEventStreamParams,
} from './resources/sessions';

export type { SessionHandle } from './lib/session';

export { Environments } from './resources/environments';
export type {
  Environment,
  DeletedEnvironment,
  EnvironmentCloudConfig,
  EnvironmentConfig,
  EnvironmentCreateParams,
  EnvironmentLimitedNetworking,
  EnvironmentUpdateParams,
  EnvironmentListParams,
  EnvironmentNetworking,
  EnvironmentPackages,
  EnvironmentResponseCloudConfig,
  EnvironmentResponseConfig,
  EnvironmentResponseLimitedNetworking,
  EnvironmentResponseNetworking,
  EnvironmentResponsePackages,
  EnvironmentResponseSelfHostedConfig,
  EnvironmentResponseUnrestrictedNetworking,
  EnvironmentSelfHostedConfig,
  EnvironmentUnrestrictedNetworking,
} from './resources/environments';

export { Files } from './resources/files';
export type {
  AgentFileMetadata,
  DeletedFile,
  FileMetadata,
  FileUploadParams,
  FileListParams,
  SessionScopedFileMetadata,
} from './resources/files';

export { Skills, Versions as SkillVersions } from './resources/skills';
export type {
  Skill,
  DeletedSkill,
  SkillCreateParams,
  SkillListParams,
  SkillVersion,
  DeletedSkillVersion,
  SkillVersionCreateParams,
  SkillVersionListParams,
} from './resources/skills';

export { Vaults, Credentials } from './resources/vaults';
export type {
  Vault,
  DeletedVault,
  VaultCreateParams,
  VaultUpdateParams,
  VaultListParams,
  VaultCredential,
  VaultCredentialAuth,
  VaultCredentialOAuthRefresh,
  VaultCredentialTokenEndpointAuth,
  DeletedVaultCredential,
  CredentialCreateAuth,
  CredentialCreateParams,
  CredentialInjectionLocation,
  CredentialUpdateParams,
  CredentialUpdateAuth,
  CredentialUpdateOAuthRefresh,
  CredentialUpdateTokenEndpointAuth,
  CredentialListParams,
  CredentialNetworking,
  CredentialOAuthRefresh,
  CredentialTokenEndpointAuth,
  CredentialValidation,
  CredentialValidationHTTPResponse,
  CredentialValidationMCPProbe,
  CredentialValidationRefresh,
} from './resources/vaults';

export { MemoryStores, Memories, MemoryVersions } from './resources/memory-stores';
export type {
  MemoryStore,
  DeletedMemoryStore,
  MemoryStoreCreateParams,
  MemoryStoreUpdateParams,
  MemoryStoreListParams,
  Memory,
  MemoryPrefix,
  MemoryListItem,
  DeletedMemory,
  MemoryContentSHA256Precondition,
  MemoryCreateBody,
  MemoryCreateParams,
  MemoryDeleteParams,
  MemoryListParams,
  MemoryRetrieveParams,
  MemoryUpdateParams,
  MemoryUpdateBody,
  MemoryView,
  MemoryVersion,
  MemoryVersionActor,
  MemoryVersionListParams,
  MemoryVersionRetrieveParams,
} from './resources/memory-stores';

export { Discovery } from './resources/discovery';
export type {
  APIGroup,
  APIGroupVersion,
  APIGroupList,
  APIResourceDescription,
  APIResourceList,
} from './resources/discovery';

export { Triggers, TriggerSessions } from './resources/triggers';
export type {
  DeletedTrigger,
  Trigger,
  TriggerAgent,
  TriggerAgentInput,
  TriggerAgentReference,
  TriggerBase,
  TriggerCreateParams,
  TriggerCronSessionMode,
  TriggerCronSource,
  TriggerCronSourceCreateParams,
  TriggerCronSourceUpdateParams,
  TriggerInputSchemaConfig,
  TriggerKafkaSource,
  TriggerKafkaSourceBase,
  TriggerKafkaSourceUpdateParams,
  TriggerListParams,
  TriggerMessagingSourceBase,
  TriggerPulsarSource,
  TriggerPulsarSourceBase,
  TriggerPulsarSourceUpdateParams,
  TriggerSessionConfig,
  TriggerSessionCreateParams,
  TriggerSessionListParams,
  TriggerSessionMode,
  TriggerSessionUpdateParams,
  TriggerSource,
  TriggerSourceCreateParams,
  TriggerSourceType,
  TriggerSourceUpdateParams,
  TriggerStatus,
  TriggerTopicSelector,
  TriggerTopicSelectorUpdate,
  TriggerUpdateParams,
} from './resources/triggers';

export { Guardrails, POLICY_EXTENSION_GROUP } from './resources/guardrails';
export type {
  DeletedGuardrail,
  Guardrail,
  GuardrailBuiltinRule,
  GuardrailCreateParams,
  GuardrailExpressionRule,
  GuardrailListParams,
  GuardrailPhase,
  GuardrailRule,
  GuardrailScope,
  GuardrailStateScope,
  GuardrailType,
  GuardrailTypeList,
  GuardrailUpdateParams,
  GuardrailVerdict,
} from './resources/guardrails';

export { ModelPrices, PRICING_EXTENSION_GROUP } from './resources/model-prices';
export type { ModelPrice, ModelPriceListParams, ModelPriceRetrieveParams } from './resources/model-prices';

export {
  APIResources,
  Catalog,
  Cloud,
  CloudAgents,
  Connections,
  Connectors,
  Functions,
  Health,
  Kafka,
  KafkaCatalog,
  KafkaConnectors,
  Packages,
  Plugins,
  Providers,
  SinkCatalog,
  SinkConnectors,
  SourceCatalog,
  SourceConnectors,
  CLOUD_EXTENSION_GROUP,
} from './resources/cloud';
export type {
  AgentProvider,
  BatchSourceConfig,
  BatchingConfig,
  CloudAPIResource,
  CloudAPIResourceList,
  ConfigFieldDefinition,
  Connection,
  ConnectionCreateParams,
  ConnectionGenericAuth,
  ConnectionHealth,
  ConnectionOAuth2,
  ConnectionSecretRef,
  ConnectionSpec,
  ConnectionStatus,
  ConnectionStatusCondition,
  ConnectionUpdateParams,
  ConnectionValidateParams,
  ConnectorDefinition,
  ConsumerConfig,
  CryptoConfig,
  FunctionConfig,
  FunctionCreateParams,
  FunctionInstanceStats,
  FunctionInstanceStatus,
  FunctionState,
  FunctionStateUpdateParams,
  FunctionStats,
  FunctionStatsBase,
  FunctionStatsInstance,
  FunctionStatus,
  FunctionStatusInstance,
  FunctionTriggerParams,
  FunctionUpdateParams,
  FunctionWindowConfig,
  KafkaConfigKeyInfo,
  KafkaConnection,
  KafkaConnectionAuthentication,
  KafkaConnectionTLS,
  KafkaSchemaRegistry,
  KafkaSchemaRegistryAuthConfig,
  KafkaConnectorCreateParams,
  KafkaConnectorInfo,
  KafkaConnectorOffset,
  KafkaConnectorOffsets,
  KafkaConnectorRestartParams,
  KafkaConnectorState,
  KafkaConnectorStateInfo,
  KafkaConnectorTaskID,
  KafkaConnectorUpdateConfigParams,
  KafkaKeyStoreConfig,
  KafkaMessage,
  KafkaOpenResponse,
  KafkaPlainAuth,
  KafkaPluginCatalogEntry,
  KafkaPluginInfo,
  KafkaPluginListParams,
  KafkaScramAuth,
  KafkaServerInfo,
  KafkaTaskInfo,
  KafkaTaskState,
  KafkaTrustStoreConfig,
  KafkaWorkerStatus,
  MessagePayloadProcessorConfig,
  OtherConnection,
  PackageMetadata,
  PackageUploadParams,
  ProducerConfig,
  PulsarConnection,
  PulsarConnectionAuthentication,
  PulsarConnectionTLS,
  RuntimeExceptionInformation,
  RuntimeResources,
  RuntimeUpdateOptions,
  SinkConfig,
  SinkCreateParams,
  SinkInstanceStatus,
  SinkStatus,
  SinkStatusInstance,
  SinkUpdateParams,
  SourceConfig,
  SourceCreateParams,
  SourceInstanceStatus,
  SourceStatus,
  SourceStatusInstance,
  SourceUpdateParams,
} from './resources/cloud';
